version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 3000:80
    depends_on:
      - node
    networks:
      - network-fc

  node:
    build:
      context: ./node
    container_name: node
    tty: true
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s sh -c "npm install && npm start"
    networks:
      - network-fc
    volumes:
      - ./node:/app

  db:
    build:
      context: ./mysql
    container_name: mysql
    tty: true
    networks:
      - network-fc
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodenginxdb
      - MYSQL_ROOT_PASSWORD=root

networks:
  network-fc:
    driver: bridge
